[tool.poetry]
name = "maksukortti"
version = "0.1.0"
description = ""
authors = ["Roni BÃ¤rman <104189902+roni-b@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
